library(ggplot2)
library(gapminder)
library(readxl)
library(gridExtra)
library(grid)
theme_set(theme_bw())
data = read_excel("D:\\Environmental_biophysics_homework\\environmental_biophysics_homewor2R\\ALL_BY_Date.xlsx",1)
data1 = read_excel("D:\\Environmental_biophysics_homework\\DAY1.xlsx")
data["DAY"] <- data1["DAY"]
print(data)
p1 = ggplot(data=data,mapping=aes(x=DAY,y=Ta))+geom_line()+geom_point(size=0.5)
p2 = ggplot(data=data,mapping=aes(x=DAY,y=RH))+geom_line()+geom_point(size=0.5)
p3 = ggplot(data=data,mapping=aes(x=DAY,y=P))+geom_line()+geom_point(size=0.5)
p4 = ggplot(data=data,mapping=aes(x=DAY,y=es))+geom_line()+geom_point(size=0.5)
p5 = ggplot(data=data,mapping=aes(x=DAY,y=ea))+geom_line()+geom_point(size=0.5)
p6 = ggplot(data=data,mapping=aes(x=DAY,y=VPD))+geom_line()+geom_point(size=0.5)
p7 = ggplot(data=data,mapping=aes(x=DAY,y=qa))+geom_line()+geom_point(size=0.5)
p8 = ggplot(data=data,mapping=aes(x=DAY,y=rou_v))+geom_line()+geom_point(size=0.5)
p9 = ggplot(data=data,mapping=aes(x=DAY,y=Cv))+geom_line()+geom_point(size=0.5)
p10=(grid.arrange(p1,p2,p3,p4,p5,p6,p7,p8,p9))
print(p10)
# dev.off() 
ggsave(p10,filename="fuck.png",dpi=300)
