library(ggplot2)
library(gapminder)
library(readxl)
library(gridExtra)
library(grid)
library(ggpubr)
theme_set(theme_bw())
data = read_excel("D:\\Environmental_biophysics_homework\\environmental_biophysics_homewor2R\\ALL_BY_Date.xlsx",1)
data1 = read_excel("D:\\Environmental_biophysics_homework\\DAY1.xlsx")
data["DAY"] <- data1["DAY"]
print(data)
p1 = ggplot(data=data,mapping=aes(x=DAY,y=Ta))+geom_line()+geom_point(size=0.2)
p2 = ggplot(data=data,mapping=aes(x=DAY,y=RH))+geom_line()+geom_point(size=0.2)
p3 = ggplot(data=data,mapping=aes(x=DAY,y=P))+geom_line()+geom_point(size=0.2)
p4 = ggplot(data=data,mapping=aes(x=DAY,y=es))+geom_line()+geom_point(size=0.2)
p5 = ggplot(data=data,mapping=aes(x=DAY,y=ea))+geom_line()+geom_point(size=0.2)
p6 = ggplot(data=data,mapping=aes(x=DAY,y=VPD))+geom_line()+geom_point(size=0.2)
p7 = ggplot(data=data,mapping=aes(x=DAY,y=qa))+geom_line()+geom_point(size=0.2)
p8 = ggplot(data=data,mapping=aes(x=DAY,y=rou_v))+geom_line()+geom_point(size=0.2)
p9 = ggplot(data=data,mapping=aes(x=DAY,y=Cv))+geom_line()+geom_point(size=0.2)
p10=(ggarrange(p1,p2,p3,nrow=3))
print(p10)
ggsave(p10,filename="fuck1.png",dpi=300)
p11=(ggarrange(p4,p5,p6,nrow=3))
print(p11)
ggsave(p11,filename="fuck2.png",dpi=300)
p12=(ggarrange(p7,p8,p9,nrow=3))
print(p12)
ggsave(p12,filename="fuck3.png",dpi=300)
# ggsave(p10,filename="fuck.png",dpi=300)

# data = read_excel("D:\\Environmental_biophysics_homework\\environmental_biophysics_homewor2R\\ALL_BY_Date.xlsx",1)
data = read_excel("D:\\Environmental_biophysics_homework\\每日48时刻均值2.xlsx")
# data["DAY"] <- data1["DAY"]
print(data)
p1 = ggplot(data=data,mapping=aes(x=doy,y=Ta))+geom_line()+geom_point(size=1)
p2 = ggplot(data=data,mapping=aes(x=doy,y=RH))+geom_line()+geom_point(size=1)
p3 = ggplot(data=data,mapping=aes(x=doy,y=P))+geom_line()+geom_point(size=1)
p4 = ggplot(data=data,mapping=aes(x=doy,y=es))+geom_line()+geom_point(size=1)
p5 = ggplot(data=data,mapping=aes(x=doy,y=ea))+geom_line()+geom_point(size=1)
p6 = ggplot(data=data,mapping=aes(x=doy,y=VPD))+geom_line()+geom_point(size=1)
p7 = ggplot(data=data,mapping=aes(x=doy,y=qa))+geom_line()+geom_point(size=1)
p8 = ggplot(data=data,mapping=aes(x=doy,y=rou_v))+geom_line()+geom_point(size=1)
p9 = ggplot(data=data,mapping=aes(x=doy,y=Cv))+geom_line()+geom_point(size=1)
p10=(ggarrange(p1,p2,p3,nrow=3))
print(p10)
ggsave(p10,filename="fuck7.png",dpi=300)
p11=(ggarrange(p4,p5,p6,nrow=3))
print(p11)
ggsave(p11,filename="fuck8.png",dpi=300)
p12=(ggarrange(p7,p8,p9,nrow=3))
print(p12)
ggsave(p12,filename="fuck9.png",dpi=300)
data = read_excel("D:\\Environmental_biophysics_homework\\environmental_biophysics_homewor2R\\month_all.xlsx",1)
# data1 = read_excel("D:\\Environmental_biophysics_homework\\DAY1.xlsx")
# data["DAY"] <- data1["DAY"]
print(data)
p1 = ggplot(data=data,mapping=aes(x=month,y=Ta,group=1))+geom_line()+geom_point(size=1)
p2 = ggplot(data=data,mapping=aes(x=month,y=RH,group=1))+geom_line()+geom_point(size=1)
p3 = ggplot(data=data,mapping=aes(x=month,y=P,group=1))+geom_line()+geom_point(size=1)
p4 = ggplot(data=data,mapping=aes(x=month,y=es,group=1))+geom_line()+geom_point(size=1)
p5 = ggplot(data=data,mapping=aes(x=month,y=ea,group=1))+geom_line()+geom_point(size=1)
p6 = ggplot(data=data,mapping=aes(x=month,y=VPD,group=1))+geom_line()+geom_point(size=1)
p7 = ggplot(data=data,mapping=aes(x=month,y=qa,group=1))+geom_line()+geom_point(size=1)
p8 = ggplot(data=data,mapping=aes(x=month,y=rou_v,group=1))+geom_line()+geom_point(size=1)
p9 = ggplot(data=data,mapping=aes(x=month,y=Cv,group=1))+geom_line()+geom_point(size=1)
p10=(ggarrange(p1,p2,p3,nrow=3))
print(p10)
ggsave(p10,filename="fuck4.png",dpi=300)
p11=(ggarrange(p4,p5,p6,nrow=3))
print(p11)
ggsave(p11,filename="fuck5.png",dpi=300)
p12=(ggarrange(p7,p8,p9,nrow=3))
print(p12)
ggsave(p12,filename="fuck6.png",dpi=300)